### ISSUE TITLE
Double border on orders button

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store_toolbar_buttons#2]
![double_border](https://cloud.githubusercontent.com/assets/1150242/19630286/9810cdd2-9944-11e6-8429-d0bcde1af3c4.png)

`div#ccm-toolbar>ul li.ccm-toolbar-search + li.pull-right a {
  border-right: none;
}`

Can be fixed with the above CSS snippet.

**Comment by Mesuva** [comment]
This bugs me too. It's more of a concrete5 issue though, as it'll affect all buttons.

In v8, this has been fixed because the buttons have been moved to the other side of the search bar. 
![screen shot 2016-10-24 at 9 53 02 am](https://cloud.githubusercontent.com/assets/1079600/19630331/53be4b50-99d0-11e6-93ea-442b785d71ca.png)

So I reckon it's not worth adding to the current package otherwise i'll potentially misalign in v8.

**Comment by jakob-fuchs** [comment]
Yeah it's more a c5 thing. I just noticed it the first time with this package and have fixed it in my theme CSS.
